### 2.2 벡터와 행렬의 연산
- 벡터와 행렬도 숫자처럼 연산 가능
- 대량의 데이터에 대한 계산을 간단한 수식으로 나타냄
- 사칙 연산과 차이 있음

- 벡터/행렬의 덧셈과 뺄셈
    - 같은 크기를 가진 두 개의 벡터나 행렬은 덧셈과 뺄셈을 할 수 있다.
    - 같은 위치끼리 있는 원소끼리 연산. 요소별 연산(element-wise)

In [1]:
x = np.array([10, 11, 12, 13, 14])
y = np.array([0, 1, 2, 3, 4])

In [2]:
x, y

(array([10, 11, 12, 13, 14]), array([0, 1, 2, 3, 4]))

In [3]:
x + y

array([10, 12, 14, 16, 18])

In [4]:
x - y

array([10, 10, 10, 10, 10])

In [6]:
np.array([[5, 6], [7, 8]]) + np.array([[10, 20], [30, 40]]) -  np.array([[1, 2], [3, 4]])

array([[14, 24],
       [34, 44]])

- 스칼라와 벡터/행렬의 곱셉
    - 벡터 x 또는 행렬 A에 스칼라 c값을 곱하는 것은 벡터 x 또는 행렬 A의 모든 원소에 스칼라 c값을 곱하는 것과 같다.
 

- 브로드 캐스팅
    - 덧셈과 뺄셈은 크기가 같은 두 벡터에 대해서만 할 수 있다. 하지만 벡터와 스칼라의 경우에는 관례적으로 다음처럼 1-벡터를 사용하여 스칼라를 벡터로 변환한 연산을 허용한다. 

- 선형조합
    - 벡터/행렬에 다음 처럼 스칼라값을 곱한 후 더하거나 뺀 것을 벡터/행렬의 선형조합이라 한다. 벡터나 행렬을 선형조합해도 크기는 변하지 않는다. 

- 벡터와 벡터의 곱셈
    - 내적에 대해서 다룬다.
    - 닷 프로덕트
    - 두 벡터의 차원이 같아야 한다. 앞의 벡터가 행벡터이고 뒤의 벡터가 열벡터여야 한다.
    - 스칼라 값이 된다. 
    

In [7]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])
x.T @ y

array([[32]])

- 가중합
    - 각각의 수에 어떤 가중치 값을 곱한 후 이 곱셉 결과들을 다시 합한 것
    - 가중치가 모두 1이면 일반적인 합을 계산한다.

In [8]:
a = np.array([[100], [80], [50]])
b = np.array([[3], [4], [5]])

a.T @ b

array([[870]])

-  가중평균
    - 